package carrerahilo;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;

/**
 *
 * @author Ana Salas
 */
public class Carrera extends javax.swing.JFrame {

    /**
     * Creates new form Carrera
     */
    public Carrera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                ImageIcon tort = new ImageIcon("/img/tortuga.gif");
                ImageIcon lieb = new ImageIcon("/img/liebre.gif");
                JProgressBar Tortuga = new JProgressBar();
                JProgressBar Liebre = new JProgressBar();
                Carrera Carrera = new Carrera();
                Carrera.getContentPane().setLayout(new GridLayout(6, 1));
                Carrera.getContentPane().setBackground(Color.WHITE);
                Carrera.setSize(800, 250);

                JPanel tortuDesplaza = new JPanel();
                tortuDesplaza.setLayout(new BorderLayout());
                JLabel tortuga = new JLabel();
                tortuDesplaza.setBackground(Color.WHITE);
                tortuDesplaza.add(tortuga, BorderLayout.WEST);
                Carrera.add(tortuDesplaza);
                Carrera.add(Tortuga);

                JPanel liebDesplaza = new JPanel();
                liebDesplaza.setLayout(new BorderLayout());
                JLabel liebre = new JLabel();
                liebDesplaza.setBackground(Color.WHITE);
                liebDesplaza.add(tortuga, BorderLayout.WEST);
                Carrera.add(liebDesplaza);
                Carrera.add(Liebre);

                Tortuga x = new Tortuga(Tortuga, 150, tortuDesplaza);
                Liebre y = new Liebre(Liebre, 100, liebDesplaza);
                JButton Comienza = new JButton("Empezar");
                Carrera.add(Comienza);
                Carrera.setVisible(true);
                x.start();
                y.start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
